import dayjs, { ConfigType, UnitType } from "dayjs";
declare type SetProps = {
    millisecond?: number;
    second?: number;
    minute?: number;
    hour?: number;
    day?: number;
    month?: number;
    year?: number;
    date?: number;
};
declare const djsParseUTC: (aTime?: ConfigType) => dayjs.Dayjs;
declare const djsMillisecondValue: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsMillisecond: (aTime?: ConfigType) => number;
declare const djsSecondValue: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsSecond: (aTime?: ConfigType) => number;
declare const djsMinuteValue: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsMinute: (aTime?: ConfigType) => number;
declare const djsHourValue: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsHour: (aTime?: ConfigType) => number;
declare const djsDayValue: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsDay: (aTime?: ConfigType) => number;
declare const djsWeekValue: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsWeek: (aTime?: ConfigType) => number;
declare const djsDateOfMonth: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsDayOfWeek: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsDayOfWeekAware: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsDayOfWeekISO: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsDayOfYear: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsWeekOfYear: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsMonthValue: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsMonth: (aTime?: ConfigType) => number;
declare const djsQuarterValue: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsQuarter: (aTime?: ConfigType) => number;
declare const djsYearValue: (aTime?: ConfigType, value?: number) => dayjs.Dayjs;
declare const djsYear: (aTime?: ConfigType) => number;
declare const djsWeekYear: (aTime?: ConfigType) => number;
declare const djsWeekInYearISO: (aTime?: ConfigType) => number;
declare const djsGet: (aTime?: ConfigType, type?: UnitType) => number;
declare const djsSet: (aTime?: ConfigType, config?: SetProps) => dayjs.Dayjs;
declare const djsDefault: (aTime: ConfigType, valueOf?: boolean) => number | dayjs.Dayjs;
declare const djsDefaultUTC: (aTime: ConfigType, valueOf?: boolean) => number | dayjs.Dayjs;
declare const djsDuration: (aTime: ConfigType, bTime: ConfigType, divisor: number) => number;
declare const djsDurationUTC: (aTime: ConfigType, bTime: ConfigType, divisor: number) => number;
export { djsDateOfMonth, djsDayOfWeek, djsDayOfWeekAware, djsDayOfWeekISO, djsSet, djsDayOfYear, djsGet, djsHour, djsMillisecond, djsMinute, djsMonth, djsQuarter, djsSecond, djsWeekInYearISO, djsWeekOfYear, djsWeekYear, djsYear, djsWeek, djsDay, djsDuration, djsDefault, djsDefaultUTC, djsDurationUTC, djsDayValue, djsHourValue, djsMillisecondValue, djsMinuteValue, djsMonthValue, djsParseUTC, djsQuarterValue, djsSecondValue, djsWeekValue, djsYearValue };
